from __future__ import annotations

from typing import Any


_LANE_KEYS = ["lane_a", "lane_b", "lane_c", "lane_d", "lane_e", "lane_f", "lane_g", "lane_h"]


def _segment_family(segment: str, subnicho: str = "") -> str:
    raw = f"{segment} {subnicho}".lower()
    if any(token in raw for token in ("barbear", "barber", "barbeiro")):
        return "barbearia"
    if any(token in raw for token in ("nutri", "nutric")):
        return "nutricionista"
    if any(token in raw for token in ("academia", "crossfit", "muscul", "fitness", "funcional", "personal")):
        return "academia"
    return "default"


_LANES: dict[str, list[dict[str, Any]]] = {
    "academia": [
        {
            "id": "academia-iron-pulse",
            "name": "Iron Pulse",
            "fallback_palette": {"primary": "#ff4d2d", "secondary": "#6b0f1a", "bg_dark": "#0a0a0a", "bg_light": "#1b1b1b", "text_dark": "#111111"},
            "blocks": {"hero_variant": "split", "services_variant": "stacked_cards", "reviews_variant": "score_wall", "faq_variant": "panel", "location_variant": "feature_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Treino de alta intensidade", "about_kicker": "Método", "about_title": "Estrutura, carga e constância para evoluir em {city}.", "about_body": "{name} organiza o treino com leitura de objetivo, rotina e progressão de carga.", "gallery_title": "Estrutura real, ritmo forte e rotina local.", "gallery_intro": "Cada quadro reforça ambiente, equipamento e sensação de treino sério em {city}.", "reviews_title": "Resultados percebidos por quem já pisa no treino.", "reviews_intro": "Avaliações, cidade e contato ajudam a decidir com segurança.", "faq_title": "Perguntas antes da primeira série.", "faq_intro": "Respostas curtas para matrícula, aula experimental e rotina.", "location_title": "Treine em {city} com rota direta.", "location_intro": "Contato e endereço aparecem sem atrito para não perder o clique.", "lifestyle_kicker": "Experiência", "contact_kicker": "Contato"},
        },
        {
            "id": "academia-neon-grid",
            "name": "Neon Grid",
            "fallback_palette": {"primary": "#41ffd9", "secondary": "#1c2bff", "bg_dark": "#061018", "bg_light": "#dffcf7", "text_dark": "#051018"},
            "blocks": {"hero_variant": "video", "services_variant": "stats_then_cards", "reviews_variant": "card_marquee", "faq_variant": "inline", "location_variant": "feature_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Treino com presença visual", "about_kicker": "Cenário", "about_title": "Ambiente noturno, energia alta e WhatsApp claro.", "about_body": "{name} apresenta movimento, intensidade e informação útil para {city}.", "gallery_title": "Frames com energia de treino em andamento.", "gallery_intro": "A galeria enfatiza luz, suor, equipamento e atmosfera da academia.", "reviews_title": "Sinais locais em fluxo contínuo.", "reviews_intro": "Depoimentos, avaliação e cidade reforçam confiança.", "faq_title": "O que o aluno pergunta antes de entrar.", "faq_intro": "FAQ direto, pensado para decisão rápida no mobile.", "location_title": "Fale pelo WhatsApp.", "location_intro": "Endereço e contato ficam visíveis para ação imediata.", "lifestyle_kicker": "Pulso", "contact_kicker": "Ação"},
        },
        {
            "id": "academia-sunset-track",
            "name": "Sunset Track",
            "fallback_palette": {"primary": "#ff7a00", "secondary": "#7f2d00", "bg_dark": "#14110f", "bg_light": "#fff1e2", "text_dark": "#1d130c"},
            "blocks": {"hero_variant": "center", "services_variant": "split_editorial", "reviews_variant": "quote_spotlight", "faq_variant": "panel", "location_variant": "split_local", "surface_style": "soft_tint"},
            "copy": {"hero_badge": "Treino com acolhimento e disciplina", "about_kicker": "Rotina", "about_title": "Disciplina diária com linguagem mais humana.", "about_body": "{name} conversa com quem quer resultado consistente, mas também precisa encaixar o treino na vida real em {city}.", "gallery_title": "Treino visto de perto, sem pose vazia.", "gallery_intro": "As imagens reforçam constância, detalhe e clareza visual.", "reviews_title": "Confiança construída na rotina.", "reviews_intro": "A reputação entra como sinal de recorrência e cuidado.", "faq_title": "Dúvidas de quem vai começar ou voltar.", "faq_intro": "Resposta curta, sem jargão e com dados confirmados.", "location_title": "Tudo pronto para visitar e começar.", "location_intro": "Mapa simples: cidade, endereço, contato e WhatsApp.", "lifestyle_kicker": "Constância", "contact_kicker": "Convite"},
        },
        {
            "id": "academia-graphite-core",
            "name": "Graphite Core",
            "fallback_palette": {"primary": "#d9d9d9", "secondary": "#7a7a7a", "bg_dark": "#090909", "bg_light": "#efefef", "text_dark": "#111111"},
            "blocks": {"hero_variant": "asymmetric", "services_variant": "stacked_cards", "reviews_variant": "editorial_case", "faq_variant": "inline", "location_variant": "split_local", "surface_style": "solid"},
            "copy": {"hero_badge": "Treino técnico", "about_kicker": "Precisão", "about_title": "Uma academia com leitura mais sóbria e técnica.", "about_body": "{name} apresenta composição limpa, mais contraste e mensagem menos promocional para destacar processo e estrutura.", "gallery_title": "Volume, técnica e acabamento visual.", "gallery_intro": "A sequência privilegia forma, materiais e execução.", "reviews_title": "Credibilidade com leitura direta.", "reviews_intro": "Avaliações aparecem com clareza para quem está comparando academias.", "faq_title": "Perguntas objetivas antes da matrícula.", "faq_intro": "Sem excesso de texto e sem promessas irreais.", "location_title": "Endereço e contato organizados.", "location_intro": "Informação funcional para quem quer decidir sem desvio.", "lifestyle_kicker": "Técnica", "contact_kicker": "Fechamento"},
        },
    ],
    "nutricionista": [
        {
            "id": "nutri-botanical-editorial",
            "name": "Botanical Editorial",
            "fallback_palette": {"primary": "#d8a64a", "secondary": "#2f5b47", "bg_dark": "#17382d", "bg_light": "#fbf6ea", "text_dark": "#173128"},
            "blocks": {"hero_variant": "center", "services_variant": "split_editorial", "reviews_variant": "quote_spotlight", "faq_variant": "panel", "location_variant": "split_local", "surface_style": "soft_tint"},
            "copy": {"hero_badge": "Acompanhamento nutricional", "about_kicker": "Escuta", "about_title": "Consulta com escuta, estratégia e plano aplicável.", "about_body": "{name} organiza acolhimento, método e atendimento local em {city}.", "gallery_title": "Consultório, rotina e sinais de confiança.", "gallery_intro": "Consulta, preparo e rotina aparecem com clareza para quem quer decidir sem pressa.", "reviews_title": "O que os pacientes percebem no acompanhamento.", "reviews_intro": "Avaliações entram como sinal de confiança clínica, com linguagem objetiva e confiável.", "faq_title": "Dúvidas antes da consulta.", "faq_intro": "Perguntas diretas sobre agenda, retorno, convênio e formato de atendimento.", "location_title": "Atendimento em {city} com acesso claro.", "location_intro": "Contato e localização aparecem com calma e legibilidade.", "lifestyle_kicker": "Cuidado", "contact_kicker": "Agendamento"},
        },
        {
            "id": "nutri-clinical-soft",
            "name": "Clinical Soft",
            "fallback_palette": {"primary": "#7ea08c", "secondary": "#3d5a4a", "bg_dark": "#f2efe8", "bg_light": "#ffffff", "text_dark": "#22362c"},
            "blocks": {"hero_variant": "split", "services_variant": "stacked_cards", "reviews_variant": "score_wall", "faq_variant": "panel", "location_variant": "split_local", "surface_style": "solid"},
            "copy": {"hero_badge": "Nutrição clínica com clareza", "about_kicker": "Processo", "about_title": "Informação leve, clínica e fácil de absorver.", "about_body": "{name} usa uma direção mais clara para reforçar confiança, leitura confortável e atendimento estruturado.", "gallery_title": "Ambiente claro e confiança gradual.", "gallery_intro": "Menos impacto dramático, mais serenidade e organização.", "reviews_title": "Credibilidade para marcar a primeira consulta.", "reviews_intro": "A reputação local sustenta o clique sem barulho visual.", "faq_title": "Perguntas práticas do primeiro atendimento.", "faq_intro": "FAQ pensado para reduzir ansiedade e simplificar a decisão.", "location_title": "Consultório e contato em evidência.", "location_intro": "Tudo legível, direto e com foco em conversão saudável.", "lifestyle_kicker": "Clareza", "contact_kicker": "Consulta"},
        },
        {
            "id": "nutri-performance-fuel",
            "name": "Performance Fuel",
            "fallback_palette": {"primary": "#00a676", "secondary": "#273469", "bg_dark": "#101820", "bg_light": "#eefaf4", "text_dark": "#14231f"},
            "blocks": {"hero_variant": "asymmetric", "services_variant": "stats_then_cards", "reviews_variant": "card_marquee", "faq_variant": "inline", "location_variant": "feature_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Nutrição para performance", "about_kicker": "Energia", "about_title": "Rotina alimentar para treinar, recuperar e manter constância.", "about_body": "{name} conecta alimentação, rotina e acompanhamento para pacientes que querem evoluir com método em {city}.", "gallery_title": "Alimentos, consulta e rotina em composição ativa.", "gallery_intro": "As imagens destacam preparo, orientação e hábitos possíveis para o dia a dia.", "reviews_title": "Confiança para quem quer acompanhamento consistente.", "reviews_intro": "Avaliações, cidade e contato ajudam o paciente a decidir com segurança.", "faq_title": "Perguntas de quem quer começar rápido.", "faq_intro": "Respostas diretas sobre consulta, retorno e forma de atendimento.", "location_title": "Atendimento em {city} com rota clara.", "location_intro": "Endereço, WhatsApp e próximos passos ficam visíveis em poucos segundos.", "lifestyle_kicker": "Performance", "contact_kicker": "Entrada"},
        },
        {
            "id": "nutri-coastal-light",
            "name": "Coastal Light",
            "fallback_palette": {"primary": "#2f8f9d", "secondary": "#d9b382", "bg_dark": "#f7fbfb", "bg_light": "#ffffff", "text_dark": "#16343a"},
            "blocks": {"hero_variant": "video", "services_variant": "split_editorial", "reviews_variant": "editorial_case", "faq_variant": "panel", "location_variant": "split_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Nutrição com leveza e direção", "about_kicker": "Bem-estar", "about_title": "Atmosfera mais leve sem perder autoridade.", "about_body": "{name} organiza acompanhamento para saúde, longevidade e reeducação alimentar.", "gallery_title": "Leveza visual com informação útil.", "gallery_intro": "A página respira mais e evita densidade excessiva.", "reviews_title": "Opiniões tratadas como confiança de marca.", "reviews_intro": "Avaliações aparecem com menos pressão e mais clareza.", "faq_title": "Perguntas antes de cuidar da rotina.", "faq_intro": "Respostas claras para quem está comparando profissionais.", "location_title": "Atendimento em {city} sem complicação.", "location_intro": "Contato, endereço e WhatsApp em arranjo mais calmo.", "lifestyle_kicker": "Leveza", "contact_kicker": "Conversa"},
        },
    ],
    "barbearia": [
        {
            "id": "barber-heritage-reserve",
            "name": "Heritage Reserve",
            "fallback_palette": {"primary": "#c9a96a", "secondary": "#3d2a18", "bg_dark": "#0d0b0a", "bg_light": "#f4ede3", "text_dark": "#1b130f"},
            "blocks": {"hero_variant": "split", "services_variant": "split_editorial", "reviews_variant": "editorial_case", "faq_variant": "panel", "location_variant": "split_local", "surface_style": "solid"},
            "copy": {"hero_badge": "Barbearia premium", "about_kicker": "Ritual", "about_title": "Corte, barba e acabamento com leitura clássica.", "about_body": "{name} valoriza detalhe, atendimento e experiência presencial em {city}.", "gallery_title": "Textura, aço, couro e acabamento.", "gallery_intro": "A galeria mostra ambiente, serviço e detalhes do ritual.", "reviews_title": "Clientes que percebem detalhe e atendimento.", "reviews_intro": "Avaliações reforçam consistência no atendimento.", "faq_title": "Antes de reservar o horário.", "faq_intro": "Perguntas práticas sobre agenda, serviços e localização.", "location_title": "Visite a barbearia em {city}.", "location_intro": "Reserva, endereço e contato ficam juntos.", "lifestyle_kicker": "Atmosfera", "contact_kicker": "Reserva"},
        },
        {
            "id": "barber-studio-mono",
            "name": "Studio Mono",
            "fallback_palette": {"primary": "#f1f1f1", "secondary": "#555555", "bg_dark": "#090909", "bg_light": "#efefef", "text_dark": "#151515"},
            "blocks": {"hero_variant": "center", "services_variant": "stacked_cards", "reviews_variant": "quote_spotlight", "faq_variant": "inline", "location_variant": "feature_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Corte com direção contemporânea", "about_kicker": "Design", "about_title": "Identidade sóbria, gráfica e precisa.", "about_body": "{name} entra numa linha mais contemporânea, com menos ornamento e mais contraste limpo.", "gallery_title": "Monocromia, recorte e presença.", "gallery_intro": "As imagens privilegiam sombra, forma e acabamento.", "reviews_title": "Confiança tratada com voz mais editorial.", "reviews_intro": "Menos excesso, mais recorte e clareza.", "faq_title": "Tudo o que importa antes de reservar.", "faq_intro": "Perguntas curtas para acelerar a escolha.", "location_title": "Agende e chegue sem complicação.", "location_intro": "O WhatsApp fica direto para reserva.", "lifestyle_kicker": "Estilo", "contact_kicker": "Reserva"},
        },
        {
            "id": "barber-copper-smoke",
            "name": "Copper Smoke",
            "fallback_palette": {"primary": "#b96d3c", "secondary": "#4e281b", "bg_dark": "#160f0d", "bg_light": "#f6ece6", "text_dark": "#231511"},
            "blocks": {"hero_variant": "asymmetric", "services_variant": "stats_then_cards", "reviews_variant": "card_marquee", "faq_variant": "panel", "location_variant": "feature_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Corte e barba com atmosfera noturna", "about_kicker": "Presença", "about_title": "Uma barbearia mais quente, escura e cinematográfica.", "about_body": "{name} usa contraste de cobre e luz baixa para enfatizar ritual, noite e personalidade.", "gallery_title": "Luz baixa, metal quente e acabamento forte.", "gallery_intro": "As imagens mostram atmosfera e proximidade.", "reviews_title": "Sinais locais em ritmo mais vivo.", "reviews_intro": "Avaliações podem ganhar movimento sem perder clareza.", "faq_title": "Perguntas para quem quer reservar hoje.", "faq_intro": "Menos texto e mais ação.", "location_title": "Localização e contato no mesmo pulso.", "location_intro": "A página fecha com convite direto para reserva.", "lifestyle_kicker": "Noite", "contact_kicker": "Agende"},
        },
        {
            "id": "barber-midnight-club",
            "name": "Midnight Club",
            "fallback_palette": {"primary": "#8b7cf7", "secondary": "#1d153d", "bg_dark": "#080712", "bg_light": "#f2efff", "text_dark": "#16112e"},
            "blocks": {"hero_variant": "video", "services_variant": "stacked_cards", "reviews_variant": "score_wall", "faq_variant": "inline", "location_variant": "split_local", "surface_style": "soft_tint"},
            "copy": {"hero_badge": "Barbearia com assinatura autoral", "about_kicker": "Assinatura", "about_title": "Direção mais ousada para marcas que querem parecer únicas.", "about_body": "{name} assume uma linha mais autoral, com luz fria, composição noturna e CTA de reserva como foco central.", "gallery_title": "Uma estética de clube privado.", "gallery_intro": "O site precisa parecer menos genérico e mais memorável.", "reviews_title": "Reputação local com recorte de marca.", "reviews_intro": "A confiança vem sem perder identidade visual.", "faq_title": "O que o cliente quer saber antes do corte.", "faq_intro": "Objetivo, curto e acionável.", "location_title": "Chegue pelo contato oficial.", "location_intro": "A navegação fecha em reserva direta.", "lifestyle_kicker": "Assinatura", "contact_kicker": "Horário"},
        },
    ],
    "default": [
        {
            "id": "default-professional-dark",
            "name": "Professional Dark",
            "fallback_palette": {"primary": "#4f46e5", "secondary": "#1f2937", "bg_dark": "#0b1220", "bg_light": "#f8fafc", "text_dark": "#0f172a"},
            "blocks": {"hero_variant": "split", "services_variant": "stacked_cards", "reviews_variant": "score_wall", "faq_variant": "panel", "location_variant": "split_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Atendimento local", "about_kicker": "Direção", "lifestyle_kicker": "Presença", "contact_kicker": "Contato"},
        },
        {
            "id": "default-editorial-light",
            "name": "Editorial Light",
            "fallback_palette": {"primary": "#0f766e", "secondary": "#155e75", "bg_dark": "#ffffff", "bg_light": "#f0fdfa", "text_dark": "#0f172a"},
            "blocks": {"hero_variant": "center", "services_variant": "split_editorial", "reviews_variant": "quote_spotlight", "faq_variant": "panel", "location_variant": "split_local", "surface_style": "solid"},
            "copy": {"hero_badge": "Serviço local", "about_kicker": "Clareza", "lifestyle_kicker": "Confiança", "contact_kicker": "Próximo passo"},
        },
        {
            "id": "default-conversion-bold",
            "name": "Conversion Bold",
            "fallback_palette": {"primary": "#ea580c", "secondary": "#7c2d12", "bg_dark": "#111827", "bg_light": "#fff7ed", "text_dark": "#111827"},
            "blocks": {"hero_variant": "asymmetric", "services_variant": "stats_then_cards", "reviews_variant": "card_marquee", "faq_variant": "inline", "location_variant": "feature_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Contato direto", "about_kicker": "Impacto", "lifestyle_kicker": "Presença", "contact_kicker": "Ação"},
        },
        {
            "id": "default-cinematic-soft",
            "name": "Cinematic Soft",
            "fallback_palette": {"primary": "#9333ea", "secondary": "#4338ca", "bg_dark": "#0f0a1f", "bg_light": "#f5f3ff", "text_dark": "#1f1235"},
            "blocks": {"hero_variant": "video", "services_variant": "stacked_cards", "reviews_variant": "editorial_case", "faq_variant": "panel", "location_variant": "feature_local", "surface_style": "soft_tint"},
            "copy": {"hero_badge": "Experiência local", "about_kicker": "Atmosfera", "lifestyle_kicker": "Marca", "contact_kicker": "Fechamento"},
        },
    ],
}


_FAMILY_COPY_DEFAULTS: dict[str, dict[str, str]] = {
    "academia": {
        "nav_about": "Estrutura",
        "nav_services": "Modalidades",
        "nav_gallery": "Ambiente",
        "nav_reviews": "Resultados",
        "nav_faq": "Dúvidas",
        "nav_location": "Local",
        "nav_lifestyle": "Ritmo",
        "nav_contact": "Matrícula",
        "services_kicker": "Treino",
        "gallery_kicker": "Ambiente",
        "reviews_kicker": "Reputação",
        "faq_kicker": "Dúvidas reais",
        "location_kicker": "Presença local",
        "location_cta_kicker": "Acesso",
        "location_cta_primary": "Falar no WhatsApp",
        "location_cta_secondary": "Ver contato",
        "modal_kicker": "Contato",
        "about_card_1_title": "Estrutura pronta",
        "about_card_1_text": "{name} aparece com ambiente, cidade e proposta alinhados para quem quer treinar em {city}.",
        "about_card_2_title": "Modalidades visíveis",
        "about_card_2_text": "Musculação, funcional ou aula experimental entram com leitura objetiva e sem promessa vazia.",
        "about_card_3_title": "Decisão rápida",
        "about_card_3_text": "Contato, prova local e CTA final trabalham para reduzir atrito na entrada.",
        "about_city_label": "Cidade",
        "about_aside_body": "Leitura direta para quem compara estrutura, localização e o melhor momento para começar.",
        "services_city_body": "Estrutura, ritmo e decisão aparecem organizados para facilitar a matrícula.",
        "contact_card_label": "Canal oficial",
        "contact_primary_label": "Falar no WhatsApp",
        "contact_secondary_label": "Abrir contato",
        "footer_contact_label": "Contato",
        "footer_location_label": "Local",
        "footer_privacy_note": "Dados factuais e privacidade preservada.",
        "contact_sub": "Envie uma mensagem para confirmar horários disponíveis, visita e primeiro treino.",
    },
    "nutricionista": {
        "nav_about": "Método",
        "nav_services": "Consulta",
        "nav_gallery": "Consultório",
        "nav_reviews": "Pacientes",
        "nav_faq": "Perguntas",
        "nav_location": "Localização",
        "nav_lifestyle": "Rotina",
        "nav_contact": "Agenda",
        "services_kicker": "Acompanhamento",
        "gallery_kicker": "Contexto",
        "reviews_kicker": "Confiança",
        "faq_kicker": "Perguntas práticas",
        "location_kicker": "Consultório",
        "location_cta_kicker": "Agenda",
        "location_cta_primary": "Agendar WhatsApp",
        "location_cta_secondary": "Ver localização",
        "modal_kicker": "Consulta",
        "about_card_1_title": "Escuta clínica",
        "about_card_1_text": "{name} aparece com consulta, cidade e contexto organizados para uma decisão mais tranquila em {city}.",
        "about_card_2_title": "Plano aplicável",
        "about_card_2_text": "A proposta valoriza acompanhamento, rotina e clareza sobre o que acontece antes e depois da consulta.",
        "about_card_3_title": "Contato claro",
        "about_card_3_text": "WhatsApp, endereço e CTA final fecham a jornada com legibilidade e confiança.",
        "about_city_label": "Atendimento",
        "about_aside_body": "Uma composição mais serena para quem precisa entender método, consultório e como marcar sem ansiedade.",
        "services_city_body": "Cidade, contato e método aparecem juntos para dar clareza antes da primeira consulta.",
        "contact_card_label": "Canal de agendamento",
        "contact_primary_label": "Agendar WhatsApp",
        "contact_secondary_label": "Abrir contato",
        "footer_contact_label": "Contato",
        "footer_location_label": "Consultório",
        "footer_privacy_note": "Dados confirmados e privacidade preservada.",
        "contact_sub": "Envie uma mensagem para confirmar agenda, modalidade de consulta e retorno.",
    },
    "barbearia": {
        "nav_about": "Ritual",
        "nav_services": "Serviços",
        "nav_gallery": "Atmosfera",
        "nav_reviews": "Clientes",
        "nav_faq": "Reserva",
        "nav_location": "Endereço",
        "nav_lifestyle": "Estilo",
        "nav_contact": "Agendar",
        "services_kicker": "Serviços",
        "gallery_kicker": "Atmosfera",
        "reviews_kicker": "Clientes",
        "faq_kicker": "Antes da reserva",
        "location_kicker": "Endereço",
        "location_cta_kicker": "Reserva",
        "location_cta_primary": "Reservar pelo WhatsApp",
        "location_cta_secondary": "Ver rota",
        "modal_kicker": "Reserva",
        "about_card_1_title": "Corte com assinatura",
        "about_card_1_text": "{name} apresenta endereço, estilo e leitura clara para quem procura corte e barba em {city}.",
        "about_card_2_title": "Ritual bem definido",
        "about_card_2_text": "Serviços, acabamento e atmosfera entram como parte da experiência, não como lista genérica.",
        "about_card_3_title": "Reserva direta",
        "about_card_3_text": "Contato, localização e CTA final foram montados para fechar horário sem rodeio.",
        "about_city_label": "Base local",
        "about_aside_body": "A página fecha esse bloco com reserva, localização e identidade forte para transformar visita em horário marcado.",
        "services_city_body": "Serviços, endereço e reserva ficam organizados para decisão rápida.",
        "contact_card_label": "Canal de reserva",
        "contact_primary_label": "Reservar no WhatsApp",
        "contact_secondary_label": "Abrir contato",
        "footer_contact_label": "Reserva",
        "footer_location_label": "Endereço",
        "footer_privacy_note": "Dados confirmados e privacidade preservada.",
        "contact_sub": "Reserve pelo WhatsApp e confirme horário, serviço e endereço antes de sair.",
    },
    "default": {
        "nav_about": "Sobre",
        "nav_services": "Serviços",
        "nav_gallery": "Visual",
        "nav_reviews": "Avaliações",
        "nav_faq": "Perguntas",
        "nav_location": "Local",
        "nav_lifestyle": "Presença",
        "nav_contact": "Contato",
        "services_kicker": "Serviços",
        "gallery_kicker": "Visual",
        "reviews_kicker": "Reputação",
        "faq_kicker": "Perguntas",
        "location_kicker": "Local",
        "location_cta_kicker": "Contato",
        "location_cta_primary": "Falar no WhatsApp",
        "location_cta_secondary": "Ver contato",
        "modal_kicker": "Contato",
        "about_card_1_title": "Presença local",
        "about_card_1_text": "{name} aparece com cidade, contato e contexto alinhados para quem está em {city}.",
        "about_card_2_title": "Serviço principal",
        "about_card_2_text": "As frentes de atendimento ficam organizadas para leitura rápida e decisão sem complicação.",
        "about_card_3_title": "Marca em contexto",
        "about_card_3_text": "Ambiente, imagem e composição sustentam o estilo do negócio com informações confirmadas.",
        "about_city_label": "Cidade",
        "about_aside_body": "Contato direto e informação confirmada para quem está decidindo agora.",
        "services_city_body": "Estrutura organizada para leitura rápida e decisão mais clara.",
        "contact_card_label": "Contato oficial",
        "contact_primary_label": "Falar no WhatsApp",
        "contact_secondary_label": "Abrir contato",
        "footer_contact_label": "Contato",
        "footer_location_label": "Local",
        "footer_privacy_note": "Dados factuais e privacidade preservada.",
        "contact_sub": "Envie uma mensagem para confirmar atendimento, endereço e melhor horário.",
    },
}


_LANE_REMIXES: dict[str, list[dict[str, Any]]] = {
    "academia": [
        {
            "id": "academia-competition-redline",
            "name": "Competition Redline",
            "fallback_palette": {"primary": "#ff1010", "secondary": "#f5f5f5", "bg_dark": "#050505", "bg_light": "#f3f3f3", "text_dark": "#111111"},
            "blocks": {"hero_variant": "fullbleed", "services_variant": "stats_then_cards", "reviews_variant": "score_wall", "faq_variant": "inline", "location_variant": "feature_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Treino competitivo", "about_kicker": "Performance", "about_title": "Energia de prova, rotina forte e presença sem promessa vazia.", "about_body": "{name} ganha uma direção mais atlética para quem procura intensidade, horários claros e decisão rápida em {city}.", "gallery_title": "Carga, suor e composição de impacto.", "gallery_intro": "As imagens entram com contraste alto, marca forte e sensação de treino em andamento.", "reviews_title": "Reputação para quem compara estrutura e ritmo.", "reviews_intro": "Score, cidade e contato aparecem com linguagem direta.", "faq_title": "Antes de puxar o primeiro treino.", "faq_intro": "Perguntas curtas sobre matrícula, aula experimental e modalidade.", "location_title": "Rota rápida para começar em {city}.", "location_intro": "Contato, endereço e CTA fecham a página com urgência controlada.", "lifestyle_kicker": "Competição", "contact_kicker": "Partida"},
        },
        {
            "id": "academia-recovery-lab",
            "name": "Recovery Lab",
            "fallback_palette": {"primary": "#66e3c4", "secondary": "#264653", "bg_dark": "#eef8f5", "bg_light": "#ffffff", "text_dark": "#17312d"},
            "blocks": {"hero_variant": "split", "services_variant": "split_editorial", "reviews_variant": "quote_spotlight", "faq_variant": "panel", "location_variant": "split_local", "surface_style": "soft_tint"},
            "copy": {"hero_badge": "Treino com técnica e cuidado", "about_kicker": "Equilíbrio", "about_title": "Força, mobilidade e constância com leitura mais limpa.", "about_body": "{name} apresenta treino orientado, rotina clara e ambiente acolhedor para quem quer evoluir com conforto.", "gallery_title": "Movimento, cuidado e espaço respirado.", "gallery_intro": "A seção reúne orientação, equipamento e rotina sustentável.", "reviews_title": "Confiança para quem está começando ou voltando.", "reviews_intro": "Avaliações ajudam a entender a experiência de outros alunos.", "faq_title": "Dúvidas antes de encaixar o treino na rotina.", "faq_intro": "Sem jargão e sem pressão artificial.", "location_title": "Comece em {city} com informação clara.", "location_intro": "O contato aparece como agendamento simples.", "lifestyle_kicker": "Cuidado", "contact_kicker": "Começo"},
        },
        {
            "id": "academia-urban-box",
            "name": "Urban Box",
            "fallback_palette": {"primary": "#facc15", "secondary": "#222222", "bg_dark": "#0b0b0b", "bg_light": "#fff7cc", "text_dark": "#181818"},
            "blocks": {"hero_variant": "asymmetric", "services_variant": "stacked_cards", "reviews_variant": "card_marquee", "faq_variant": "inline", "location_variant": "feature_local", "surface_style": "solid"},
            "copy": {"hero_badge": "Treino urbano", "about_kicker": "Ritmo", "about_title": "Uma academia com linguagem de rua, foco e endereço claro.", "about_body": "{name} destaca rotina, modalidades e decisão sem enrolação.", "gallery_title": "Blocos fortes, equipamento e cidade.", "gallery_intro": "A página ganha ritmo mais direto e menos aparência de template.", "reviews_title": "Sinais locais que sustentam a escolha.", "reviews_intro": "A reputação aparece junto da decisão de contato.", "faq_title": "O que decidir antes de entrar.", "faq_intro": "Perguntas rápidas para levar ao WhatsApp.", "location_title": "Chegue ao treino em {city}.", "location_intro": "A rota de ação é curta: ver, entender, falar.", "lifestyle_kicker": "Rua", "contact_kicker": "Entrada"},
        },
        {
            "id": "academia-endurance-blue",
            "name": "Endurance Blue",
            "fallback_palette": {"primary": "#38bdf8", "secondary": "#0f172a", "bg_dark": "#07111f", "bg_light": "#eaf6ff", "text_dark": "#0f172a"},
            "blocks": {"hero_variant": "video", "services_variant": "split_editorial", "reviews_variant": "editorial_case", "faq_variant": "panel", "location_variant": "split_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Treino de longo prazo", "about_kicker": "Evolução", "about_title": "Constância, resistência e experiência mais premium.", "about_body": "{name} apresenta ritmo mais cinematográfico para quem procura estrutura, acompanhamento e progresso em {city}.", "gallery_title": "Uma sequência visual de evolução.", "gallery_intro": "A galeria mostra percurso, rotina e progresso.", "reviews_title": "Credibilidade para continuar voltando.", "reviews_intro": "Depoimentos e sinais locais reforçam permanência.", "faq_title": "Antes de manter a rotina.", "faq_intro": "Perguntas para entender encaixe, horário e contato.", "location_title": "Endereço com rota limpa.", "location_intro": "O site fecha com WhatsApp claro.", "lifestyle_kicker": "Evolução", "contact_kicker": "Ritmo"},
        },
    ],
    "nutricionista": [
        {
            "id": "nutri-hormone-care",
            "name": "Hormone Care",
            "fallback_palette": {"primary": "#9f7aea", "secondary": "#2f2546", "bg_dark": "#f7f2ff", "bg_light": "#ffffff", "text_dark": "#251f33"},
            "blocks": {"hero_variant": "split", "services_variant": "stacked_cards", "reviews_variant": "quote_spotlight", "faq_variant": "panel", "location_variant": "split_local", "surface_style": "soft_tint"},
            "copy": {"hero_badge": "Nutrição com escuta e precisão", "about_kicker": "Acolhimento", "about_title": "Cuidado nutricional com leitura delicada e estratégica.", "about_body": "{name} acolhe consultas que pedem escuta, rotina e acompanhamento próximo.", "gallery_title": "Detalhes leves, consultório e confiança.", "gallery_intro": "A página evita excesso clínico e melhora a sensação de cuidado.", "reviews_title": "Pacientes, confiança e evolução possível.", "reviews_intro": "Avaliações aparecem sem tom agressivo.", "faq_title": "Perguntas antes da primeira consulta.", "faq_intro": "Tudo com linguagem clara e sem pressão.", "location_title": "Atendimento em {city} com acesso simples.", "location_intro": "Endereço e contato aparecem com calma e legibilidade.", "lifestyle_kicker": "Cuidado", "contact_kicker": "Consulta"},
        },
        {
            "id": "nutri-family-table",
            "name": "Family Table",
            "fallback_palette": {"primary": "#d49a3a", "secondary": "#3e5f45", "bg_dark": "#fff8ee", "bg_light": "#ffffff", "text_dark": "#2a251b"},
            "blocks": {"hero_variant": "center", "services_variant": "split_editorial", "reviews_variant": "editorial_case", "faq_variant": "panel", "location_variant": "feature_local", "surface_style": "solid"},
            "copy": {"hero_badge": "Alimentação possível na vida real", "about_kicker": "Rotina", "about_title": "Estratégia nutricional que cabe na mesa e na semana.", "about_body": "{name} apresenta organização alimentar sem radicalismo.", "gallery_title": "Comida, rotina e orientação clara.", "gallery_intro": "A página troca estética fria por proximidade e clareza.", "reviews_title": "Confiança de quem sentiu o processo acontecer.", "reviews_intro": "Depoimentos aparecem com tom de continuidade.", "faq_title": "Antes de mudar a rotina alimentar.", "faq_intro": "Perguntas sobre consulta, retorno e acompanhamento.", "location_title": "Agende em {city} sem complicar.", "location_intro": "Contato e localização ficam no mesmo raciocínio.", "lifestyle_kicker": "Mesa", "contact_kicker": "Agenda"},
        },
        {
            "id": "nutri-sports-lab",
            "name": "Sports Lab",
            "fallback_palette": {"primary": "#b7ff3c", "secondary": "#111827", "bg_dark": "#101318", "bg_light": "#f3ffe1", "text_dark": "#111827"},
            "blocks": {"hero_variant": "fullbleed", "services_variant": "stats_then_cards", "reviews_variant": "score_wall", "faq_variant": "inline", "location_variant": "feature_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Nutrição esportiva com método", "about_kicker": "Performance", "about_title": "Plano alimentar para quem mede evolução, treino e rotina.", "about_body": "{name} assume uma direção mais esportiva quando o lead pede intensidade, objetivo e acompanhamento técnico.", "gallery_title": "Energia, treino e estratégia visual.", "gallery_intro": "A composição conversa com rotina ativa e decisão rápida.", "reviews_title": "Prova para quem compara performance e confiança.", "reviews_intro": "Score e depoimentos entram com mais impacto.", "faq_title": "Antes de ajustar treino e alimentação.", "faq_intro": "FAQ curto, prático e direto ao WhatsApp.", "location_title": "Atendimento esportivo em {city}.", "location_intro": "A rota para marcar consulta fica evidente.", "lifestyle_kicker": "Performance", "contact_kicker": "Plano"},
        },
        {
            "id": "nutri-premium-clinic",
            "name": "Premium Clinic",
            "fallback_palette": {"primary": "#d6b86a", "secondary": "#102a43", "bg_dark": "#0d1f31", "bg_light": "#f7f2e7", "text_dark": "#102033"},
            "blocks": {"hero_variant": "asymmetric", "services_variant": "stacked_cards", "reviews_variant": "card_marquee", "faq_variant": "panel", "location_variant": "split_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Atendimento nutricional premium", "about_kicker": "Autoridade", "about_title": "Consultório com presença elegante e decisão segura.", "about_body": "{name} reforça autoridade, privacidade e atendimento bem conduzido.", "gallery_title": "Consultório, detalhe e acabamento de marca.", "gallery_intro": "A página usa respiro e contraste para comunicar cuidado mais exclusivo.", "reviews_title": "Confiança tratada com cuidado editorial.", "reviews_intro": "A reputação aparece como autoridade local.", "faq_title": "Perguntas de quem busca atendimento qualificado.", "faq_intro": "Informação objetiva sem banalizar a consulta.", "location_title": "Localização e contato com leitura premium.", "location_intro": "O WhatsApp final mantém elegância e clareza.", "lifestyle_kicker": "Autoridade", "contact_kicker": "Agendar"},
        },
    ],
    "barbearia": [
        {
            "id": "barber-old-money-green",
            "name": "Old Money Green",
            "fallback_palette": {"primary": "#d9b86c", "secondary": "#12392d", "bg_dark": "#071c16", "bg_light": "#f3ead8", "text_dark": "#14221c"},
            "blocks": {"hero_variant": "center", "services_variant": "split_editorial", "reviews_variant": "editorial_case", "faq_variant": "panel", "location_variant": "split_local", "surface_style": "solid"},
            "copy": {"hero_badge": "Barbearia clássica", "about_kicker": "Tradição", "about_title": "Corte com aparência de clube reservado e atenção ao detalhe.", "about_body": "{name} ganha uma presença mais elegante para valorizar tradição, reserva e acabamento em {city}.", "gallery_title": "Madeira, metal e ritual em composição premium.", "gallery_intro": "A galeria deixa de parecer catálogo e vira atmosfera.", "reviews_title": "Clientes que voltam pelo atendimento e acabamento.", "reviews_intro": "A reputação é tratada como confiança recorrente.", "faq_title": "Antes de reservar o horário.", "faq_intro": "Serviços, agenda e chegada em linguagem direta.", "location_title": "Encontre a barbearia em {city}.", "location_intro": "Contato e endereço fecham a reserva sem atrito.", "lifestyle_kicker": "Tradição", "contact_kicker": "Reserva"},
        },
        {
            "id": "barber-street-red",
            "name": "Street Red",
            "fallback_palette": {"primary": "#ef233c", "secondary": "#111111", "bg_dark": "#050505", "bg_light": "#f7f7f7", "text_dark": "#111111"},
            "blocks": {"hero_variant": "fullbleed", "services_variant": "stats_then_cards", "reviews_variant": "score_wall", "faq_variant": "inline", "location_variant": "feature_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Corte urbano", "about_kicker": "Atitude", "about_title": "Uma barbearia com presença forte, direta e memorável.", "about_body": "{name} assume uma linha mais urbana quando a marca precisa parecer atual, rápida e com personalidade.", "gallery_title": "Rua, contraste e acabamento em destaque.", "gallery_intro": "O visual trabalha impacto e clareza no primeiro scroll.", "reviews_title": "Prova local com energia de marca.", "reviews_intro": "Score e comentários entram com ritmo mais agressivo.", "faq_title": "O que saber antes de chamar.", "faq_intro": "FAQ curto para levar o usuário direto ao WhatsApp.", "location_title": "Reserve em {city} sem enrolação.", "location_intro": "Endereço, contato e ação aparecem no mesmo bloco.", "lifestyle_kicker": "Atitude", "contact_kicker": "Chamar"},
        },
        {
            "id": "barber-atelier-light",
            "name": "Atelier Light",
            "fallback_palette": {"primary": "#1f2937", "secondary": "#c9a46a", "bg_dark": "#f6f1ea", "bg_light": "#ffffff", "text_dark": "#1f2937"},
            "blocks": {"hero_variant": "split", "services_variant": "stacked_cards", "reviews_variant": "quote_spotlight", "faq_variant": "panel", "location_variant": "split_local", "surface_style": "soft_tint"},
            "copy": {"hero_badge": "Barbearia autoral", "about_kicker": "Atelier", "about_title": "Corte e barba com estética mais clara, limpa e autoral.", "about_body": "{name} funciona como atelier de atendimento, com foco em detalhe e experiência sem peso visual excessivo.", "gallery_title": "Acabamento, luz e proximidade.", "gallery_intro": "A composição respira mais e valoriza o trabalho manual.", "reviews_title": "Clientes e confiança com tom mais humano.", "reviews_intro": "Avaliações ficam leves, mas convincentes.", "faq_title": "Perguntas antes do atendimento.", "faq_intro": "Informação prática sobre serviço, reserva e chegada.", "location_title": "Chegue com clareza em {city}.", "location_intro": "Contato e rota aparecem sem poluição.", "lifestyle_kicker": "Atelier", "contact_kicker": "Horário"},
        },
        {
            "id": "barber-brutal-mono",
            "name": "Brutal Mono",
            "fallback_palette": {"primary": "#ffffff", "secondary": "#000000", "bg_dark": "#000000", "bg_light": "#eeeeee", "text_dark": "#111111"},
            "blocks": {"hero_variant": "asymmetric", "services_variant": "split_editorial", "reviews_variant": "card_marquee", "faq_variant": "inline", "location_variant": "feature_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Corte sem excesso", "about_kicker": "Contraste", "about_title": "Uma barbearia com linguagem gráfica, seca e marcante.", "about_body": "{name} usa alto contraste e composição mais ousada para fugir da página escura comum.", "gallery_title": "Preto, branco e recorte preciso.", "gallery_intro": "A identidade vem da composição, não de ornamento.", "reviews_title": "Reputação em blocos fortes.", "reviews_intro": "Avaliações ganham peso visual e leitura rápida.", "faq_title": "Perguntas objetivas.", "faq_intro": "Sem discurso longo: serviço, horário, contato.", "location_title": "Endereço e reserva no mesmo golpe.", "location_intro": "A página fecha com clareza e impacto.", "lifestyle_kicker": "Contraste", "contact_kicker": "Reservar"},
        },
    ],
    "default": [
        {
            "id": "default-health-trust",
            "name": "Health Trust",
            "fallback_palette": {"primary": "#0ea5a4", "secondary": "#164e63", "bg_dark": "#ecfeff", "bg_light": "#ffffff", "text_dark": "#12343b"},
            "blocks": {"hero_variant": "split", "services_variant": "stacked_cards", "reviews_variant": "quote_spotlight", "faq_variant": "panel", "location_variant": "split_local", "surface_style": "soft_tint"},
            "copy": {"hero_badge": "Atendimento com confiança", "about_kicker": "Cuidado", "lifestyle_kicker": "Confiança", "contact_kicker": "Agendar"},
        },
        {
            "id": "default-local-craft",
            "name": "Local Craft",
            "fallback_palette": {"primary": "#b45309", "secondary": "#365314", "bg_dark": "#1c160f", "bg_light": "#fff7ed", "text_dark": "#21160d"},
            "blocks": {"hero_variant": "center", "services_variant": "split_editorial", "reviews_variant": "editorial_case", "faq_variant": "panel", "location_variant": "feature_local", "surface_style": "solid"},
            "copy": {"hero_badge": "Serviço local com presença", "about_kicker": "Ofício", "lifestyle_kicker": "Detalhe", "contact_kicker": "Contato"},
        },
        {
            "id": "default-technical-precision",
            "name": "Technical Precision",
            "fallback_palette": {"primary": "#60a5fa", "secondary": "#1e293b", "bg_dark": "#0f172a", "bg_light": "#eff6ff", "text_dark": "#0f172a"},
            "blocks": {"hero_variant": "asymmetric", "services_variant": "stats_then_cards", "reviews_variant": "score_wall", "faq_variant": "inline", "location_variant": "split_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Serviço técnico", "about_kicker": "Precisão", "lifestyle_kicker": "Processo", "contact_kicker": "Solicitar"},
        },
        {
            "id": "default-hospitality-warm",
            "name": "Hospitality Warm",
            "fallback_palette": {"primary": "#f97316", "secondary": "#7c2d12", "bg_dark": "#21130b", "bg_light": "#fff3e8", "text_dark": "#24150c"},
            "blocks": {"hero_variant": "video", "services_variant": "split_editorial", "reviews_variant": "card_marquee", "faq_variant": "panel", "location_variant": "feature_local", "surface_style": "outline"},
            "copy": {"hero_badge": "Experiência local", "about_kicker": "Recepção", "lifestyle_kicker": "Ambiente", "contact_kicker": "Reservar"},
        },
    ],
}


_LANE_COPY_ENRICHMENTS: dict[str, dict[str, str]] = {
    "academia-iron-pulse": {
        "services_kicker": "Treino real",
        "gallery_kicker": "Carga e ambiente",
        "reviews_kicker": "Prova local",
        "faq_kicker": "Antes da primeira série",
        "location_cta_title": "Fale com a equipe e entre no ritmo.",
        "location_cta_body": "WhatsApp, endereço e decisão aparecem juntos para não perder impulso.",
        "contact_headline": "Pronto para começar o treino com estrutura de verdade?",
    },
    "academia-neon-grid": {
        "services_kicker": "Alta energia",
        "gallery_kicker": "Luz e movimento",
        "reviews_kicker": "Sinais da cidade",
        "faq_kicker": "O que trava o clique",
        "location_cta_title": "Chegue pelo canal mais rápido.",
        "location_cta_body": "A página empurra para ação imediata, sem etapa morta nem menu inútil.",
        "contact_headline": "Entre agora e puxe seu próximo treino para perto.",
    },
    "academia-sunset-track": {
        "services_kicker": "Rotina viável",
        "gallery_kicker": "Treino de perto",
        "reviews_kicker": "Confiança da rotina",
        "faq_kicker": "Antes de voltar ou começar",
        "location_cta_title": "Veja o caminho e marque sua entrada.",
        "location_cta_body": "Cidade, contato e estrutura aparecem com leitura mais humana e direta.",
        "contact_headline": "Seu próximo treino pode começar com menos ruído e mais constância.",
    },
    "academia-graphite-core": {
        "services_kicker": "Método",
        "gallery_kicker": "Forma e execução",
        "reviews_kicker": "Credibilidade",
        "faq_kicker": "Perguntas objetivas",
        "location_cta_title": "Fale com a academia sem desvio.",
        "location_cta_body": "A informação fecha o site com clareza técnica, contato rápido e endereço visível.",
        "contact_headline": "Quer confirmar a estrutura e falar direto com a equipe?",
    },
    "nutri-botanical-editorial": {
        "services_kicker": "Consulta e método",
        "gallery_kicker": "Consultório e rotina",
        "reviews_kicker": "Pacientes",
        "faq_kicker": "Antes da consulta",
        "location_cta_title": "Agende com calma e contato direto.",
        "location_cta_body": "Consultório, WhatsApp e próximos passos aparecem sem poluição visual.",
        "contact_headline": "Pronto para começar um acompanhamento nutricional com direção clara?",
    },
    "nutri-clinical-soft": {
        "services_kicker": "Atendimento clínico",
        "gallery_kicker": "Ambiente claro",
        "reviews_kicker": "Confiança gradual",
        "faq_kicker": "Perguntas do primeiro atendimento",
        "location_cta_title": "Veja o consultório e fale sem atrito.",
        "location_cta_body": "Tudo foi organizado para leitura confortável, decisão rápida e contato saudável.",
        "contact_headline": "Quer tirar dúvidas e marcar sua primeira consulta?",
    },
    "nutri-performance-fuel": {
        "services_kicker": "Estratégia e performance",
        "gallery_kicker": "Rotina ativa",
        "reviews_kicker": "Resultados percebidos",
        "faq_kicker": "Perguntas de quem quer começar logo",
        "location_cta_title": "Confirme pelo WhatsApp e avance com segurança.",
        "location_cta_body": "A rota de contato aparece com mais energia para quem compara profissionais e quer agir agora.",
        "contact_headline": "Vamos transformar objetivo em rotina alimentar aplicável?",
    },
    "nutri-coastal-light": {
        "services_kicker": "Cuidado nutricional",
        "gallery_kicker": "Leveza com contexto",
        "reviews_kicker": "Opiniões de confiança",
        "faq_kicker": "Dúvidas antes de cuidar da rotina",
        "location_cta_title": "Fale com leveza, mas com direção.",
        "location_cta_body": "Consultório, contato e ação aparecem num arranjo mais calmo e muito mais legível.",
        "contact_headline": "Sua consulta pode começar com uma conversa mais clara.",
    },
    "barber-heritage-reserve": {
        "services_kicker": "Corte e ritual",
        "gallery_kicker": "Detalhe e textura",
        "reviews_kicker": "Clientes recorrentes",
        "faq_kicker": "Antes do horário",
        "location_cta_title": "Reserve pelo WhatsApp e veja a rota.",
        "location_cta_body": "A reserva fecha o site com presença clássica, rota objetiva e menos fricção.",
        "contact_headline": "Quer garantir seu horário com corte, barba e acabamento bem alinhados?",
    },
    "barber-studio-mono": {
        "services_kicker": "Assinatura contemporânea",
        "gallery_kicker": "Forma e recorte",
        "reviews_kicker": "Confiança editorial",
        "faq_kicker": "Antes de reservar",
        "location_cta_title": "Agende sem excesso de conversa.",
        "location_cta_body": "O CTA é seco, direto e acompanhado de localização para fechar a decisão na hora.",
        "contact_headline": "Seu próximo corte pode ser marcado agora, sem complicação.",
    },
    "barber-copper-smoke": {
        "services_kicker": "Noite e acabamento",
        "gallery_kicker": "Luz baixa e cobre",
        "reviews_kicker": "Sinais locais",
        "faq_kicker": "Perguntas de quem quer reservar hoje",
        "location_cta_title": "Abra o WhatsApp e puxe sua reserva.",
        "location_cta_body": "Contato, rota e sensação de convite trabalham no mesmo pulso visual.",
        "contact_headline": "Vamos confirmar seu horário e deixar o corte na agenda?",
    },
    "barber-midnight-club": {
        "services_kicker": "Marca autoral",
        "gallery_kicker": "Clube e atmosfera",
        "reviews_kicker": "Reputação de marca",
        "faq_kicker": "O cliente quer saber",
        "location_cta_title": "Chegue pelo contato oficial e feche a reserva.",
        "location_cta_body": "A navegação termina em contato direto, identidade forte e caminho sem distrações.",
        "contact_headline": "Pronto para reservar um horário com assinatura mais autoral?",
    },
}


def resolve_visual_lane(
    *,
    segment: str = "",
    subnicho: str = "",
    visual_lane: str = "",
) -> dict[str, Any]:
    family = _segment_family(segment, subnicho)
    lanes = list(_LANES.get(family) or _LANES["default"])
    lanes.extend(_LANE_REMIXES.get(family) or _LANE_REMIXES.get("default") or [])
    try:
        index = _LANE_KEYS.index(str(visual_lane or "").strip())
    except ValueError:
        index = 0
    lane = dict(lanes[index % len(lanes)])
    lane_copy = dict(_FAMILY_COPY_DEFAULTS.get(family, {}))
    lane_copy.update(_LANE_COPY_ENRICHMENTS.get(str(lane.get("id") or ""), {}))
    lane_copy.update(lane.get("copy") or {})
    lane["copy"] = lane_copy
    return {
        "family": family,
        **lane,
    }
